digitalhuman:
  resource-pool:
    client:
      resourcePoolUrl: http://192.168.8.109:8082
  hypervisor:
    process:
      config:
        command: /home/work/digital-human-proxy-server/bin/BRTCProxy -UE4=${ue4} -RTC=${rtcUrl} -UID=${userId} -ROOMNAME=${roomId} -APPID=${appId} -TOKEN=${token} -KILLSELF_WHEN_OTHERS_LEAVING -AUDIO_IN_SAMPLE_RATE=16000
        workDir: /home/work/digital-human-proxy-server/bin
    hypervisor:
      config:
        hypervisorType: INTER_PROCESS
        subProcessLogDir: /home/work/digital-human-proxy-server/logs/sub-process
        subProcessLogDateFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
        initialStatus: IDLE
        auto-release-interval-milliseconds: 15000
        healthEnabled: true
    resource:
      config:
        resourceType: PROXY_SERVER
        ports:
          host: 8080
          health: 8080
