server:
  port: 8889
  timeout: 1000
digitalhuman:
  name: liuyishuangzi
  age: 22

#配置mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gsc?useUnique=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 718988
    driverClassName: com.mysql.jdbc.Driver
    #Druid连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties.druid.stat.mergeSql: true;
    connectionProperties.druid.stat.slowSqlMillis: 5000
#mybatis:
#  #加载mapper配置类
#  mapper-locations: classpath:mapper/*.xml
#  #加载mapper实体类
#  type-aliases-package: com.huawei.entity