apiVersion: v1
kind: Service
metadata:
  name: dockertest
  namespace: default
  labels:
    app: dockertest
spec:
  type: NodePort
  ports:
    - port: 8889
      nodePort: 8889 #service对外开放端口
  selector:
    app: dockertest
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: dockertest #名称
  labels:
    app: dockertest #标注
spec:
  replicas: 2 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: dockertest
  template:
    metadata:
      labels:
        app: dockertest
    spec:
      containers: #docker容器的配置
      - name: dockertest
        image: liuyucheng02/springboot:1.0.4 # pull镜像的地址 ip:prot/dir/images:tag
#          image: 10.233.0.100:5000:springboot/helloworld:1.0.3
        imagePullPolicy: Always #pull镜像时机，
        ports:
        - containerPort: 8889 #容器对外开放端口
        volumeMounts:
          - name: conf
            mountPath: /home/springboot/config/application.yaml
            subPath: application.yaml
          - name: log
            mountPath: /home/springboot/log
          - name: pic
            mountPath: /home/springboot/config/pic
      volumes:
      - name: conf
        configMap:
          name: helloworld
      - name: log
        hostPath:
          path: /data/logs/hello/
          type: DirectoryOrCreate
      - name: pic
        hostPath:
          path: /data/pic/hello/
          type: DirectoryOrCreate