## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/gsc?useUnicode=true&characterEncoding=utf8
    username: bdl
    password: Bdl@2020
    driverClassName: com.mysql.jdbc.Driver
#master.datasource.username=bdl
#master.datasource.password=Bdl@2020


server:
  port: 8082

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 1000        #连接超时时间毫秒
  jedis:
    pool:
      max-active: 100  #连接池最大连接数（使用负值表示没有限制）
      max-wait: 1      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10     #连接池中的最大空闲连接
      min-idle: 0      #连接池中的最小空闲连接

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#log4j.logger.com.ibatis=DEBUG
#log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=DEBUG
#log4j.logger.com.ibatis.common.jdbc.ScriptRunner=DEBUG
#log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG
#log4j.logger.Java.sql.Connection=DEBUG
#log4j.logger.java.sql.Statement=DEBUG
#log4j.logger.java.sql.PreparedStatement=DEBUG　


